### ISSUE TITLE
error setting model_label in unbinned likelihood fit

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#100]
When using
 LLfit.model_label = 'pdf' 
in an unbinnded likliehood fit LLfit = UnbinnnedFit() 
to get rid of the default and meaningless name "model 0"
i get the following error 
/usr/lib/python3.6/site-packages/kafe2/fit/_base/plot.py in update_plot_kwargs(self, plot_type, plot_kwargs)
    358                 "Cannot set custom plot keyword arguments "
    359                 "for plot type '{}': no plot with this type defined "
--> 360                 "for this adapter!".format(plot_type))
    361 
    362         # remove keys set to '__default__': the defaults will be substituted in

ValueError: Cannot set custom plot keyword arguments for plot type 'model_error_band': no plot with this type defined for this adapter!

**Comment by Citiroller** [comment]
Fixed as of e412e07.
When initializing the Plot object, there were no checks if the according subplots to the labels were available.
In this case, unbinned fits do not support a model_error_band, but the label for it was set anyways.
