### ISSUE TITLE
Insufficient nan detection during histogram fit

### ISSUE THREAD

**Issue by a-monsch** [dsavoiu/kafe2#109]
**Description**

When fitting a histogram with the standard cost function (`HistCostFunction_NegLogLikelihood(data_point_distribution='poisson')`), the problem often arises that the function to be fitted gets `nan` as arguments from the minimizer after a few calls.

Pretty fast all arguments (if there are a lot of arguments) are then only `nan`. Accordingly, the fit "results" consist only of `nan`.

**Reproduction**

The only difference between "iminuit" and "scipy" as minimizer is that iminuit allows more time to scan the parameter space (?). The behaviour and the result are similar. For this reason "scipy" can be replaced by "iminuit" in the following code. This suggests that it is something kafe2 internal (?).

```
import kafe2 as K2
import numpy as np
import os

counter = 0


def gauss(x, m, s):
    return (-0.5 * ((x - m) / s) ** 2) / np.sqrt(2 * np.pi * s ** 2)


def used_func(x, u1=0.45, u2=0.45, m1=-2.0, m2=2.0, s1=1.0, s2=1.0, a=0.1):
    global counter
    counter += 1
    if counter % 1000 == 0:
        os.system("clear")
        for key, val in locals().items():
            if key != "x":
                print(f"{key} = {val}")
    return u1 * gauss(x, m1, s1) + u2 * gauss(x, m2, s2) + a


if __name__ == "__main__":
    loc_, scale_, size_ = 0.0, 3.0, 10000
    np.random.seed(0)
    random_numbers_ = list(np.random.uniform(loc_ - 3 * scale_, loc_ + 3 * scale_, int(1 * size_)))
    random_numbers_ += list(np.random.normal(loc=-2, scale=1, size=int(1 * size_)))
    random_numbers_ += list(np.random.normal(loc=2, scale=1.5, size=int(1 * size_)))
    
    h_data_ = K2.HistContainer(n_bins=100, bin_range=(loc_ - 3 * scale_, loc_ + 3 * scale_), fill_data=random_numbers_)
    
    h_fit_ = K2.HistFit(h_data_, used_func, minimizer="iminuit")
    # Addition that changes nothing.
    # h_fit_.limit_parameter("u1", (0.0001, 1.0))
    # h_fit_.limit_parameter("u2", (0.0001, 1.0))
    # h_fit_.limit_parameter("m1", (loc_ - 3 * scale_, 0.0))
    # h_fit_.limit_parameter("m2", (0.0, loc_ + 3 * scale_))
    # h_fit_.limit_parameter("s1", (0.0001, 10.0))
    # h_fit_.limit_parameter("s2", (0.0001, 10.0))
    # h_fit_.limit_parameter("a", (0.0, 10.0))
    # h_fit_.set_all_parameter_values([0.45, 0.45, -2.0, 2.0, 1.0, 1.0, 0.1])
    h_fit_.do_fit()
    print(h_fit_.parameter_values)
```

**Traceback**

Not surprisingly, this comes very quickly at the beginning (but is overwritten by the `os.system("clear")`).

````
Warning: the cost function has been evaluated as infinite. The fit might not converge correctly.
/home/amonsch/Desktop/kafe2_tests/venv/lib/python3.6/site-packages/kafe2/fit/histogram
/model.py:103: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
the requested tolerance from being achieved. The error may be underestimated.
_int_val[_i], _ = integrate.quad(_integrand_func, _a, _b)
/home/amonsch/Desktop/kafe2_tests/venv/lib/python3.6/site-packages/scipy/stats
/_discrete_distns.py:598: RuntimeWarning: invalid value encountered in greater_equal return mu >= 0
````

**Expectations**

 - The fit should be terminated as soon as 'nan' appears, since the function and thus the model contained in the cost function has only 'nan' in the output, i.e. is meaningless.
 - At least with "scipy" as the minimizer, an 'AssertionError' comes at the end, although the minimizer seems to have gotten out of the 'nan' at the end. With "iminuit" no such error occurs and the `nan` as results are used further. At this point draw the additional attention of the user to it in some way ("iminuit" case)?
 - A warning is already being displayed... at this point a naive question: why is there only one warning when an `inf` appears?

So far the minimizer seems to continue to work. At this point I'm not sure if it "finds" a "minimum" or if it aborts after the maximum number of calls. Because as I said before: the fit "results" are accordingly only 'nan'. (Or I overlook an obvious setting in this case.)

**Used kafe2 version**

Current Master branch (08.03.2020)

**System:**

 - OS: Ubuntu 18.04, Windows 10
 - Python Version 3.6.9, 3.8.2

**Additionally**

The part may be inserted if a step-by-step insight into the minimizer is made.
But mainly there should be a better early termination.
With the cost function "chi2" I could not observe this behavior yet.

**Comment by JohannesGaessler** [comment]
Please take a close look at your script.
Your definition of a Gaussian distribution is incorrect (you forgot to apply the exponential function).
I was able to achieve the expected results with the following script:

`import kafe2 as K2
import numpy as np
import matplotlib.pyplot as plt

counter = 0


def gauss(x, m, s):
    return np.exp(-0.5 * ((x - m) / s) ** 2) / np.sqrt(2 * np.pi * s ** 2)


def used_func(x, u1=0.45, u2=0.45, m1=-2.0, m2=2.0, s1=1.0, s2=1.0, a=0.1):
    global counter
    counter += 1
    return u1 * gauss(x, m1, s1) + u2 * gauss(x, m2, s2) + a


if __name__ == "__main__":
    loc_, scale_, size_ = 0.0, 3.0, 10000
    np.random.seed(0)
    random_numbers_ = list(np.random.uniform(loc_ - 3 * scale_, loc_ + 3 * scale_, int(1 * size_)))
    random_numbers_ += list(np.random.normal(loc=-2, scale=1, size=int(1 * size_)))
    random_numbers_ += list(np.random.normal(loc=2, scale=1.5, size=int(1 * size_)))

    h_data_ = K2.HistContainer(n_bins=100, bin_range=(loc_ - 3 * scale_, loc_ + 3 * scale_),
                               fill_data=random_numbers_)

    h_fit_ = K2.HistFit(h_data_, used_func, minimizer="iminuit")
    # Uncomment these lines to limit the parameters to positive values.
    # This should make convergence ~6 times faster
    #h_fit_.limit_parameter("u1", (1e-9, None))
    #h_fit_.limit_parameter("u2", (1e-9, None))
    #h_fit_.limit_parameter("s1", (1e-9, None))
    #h_fit_.limit_parameter("s2", (1e-9, None))
    #h_fit_.limit_parameter("a", (1e-9, None))
    h_fit_.do_fit()

    print(h_fit_.parameter_values)
    print(counter)

    h_plot_ = K2.Plot(h_fit_)
    h_plot_.plot()
    plt.show()
`

I'm not sure how much can be done on our end regarding fit convergence.
Ideally any back end we use would be able to handle the cost function becoming infinite.
Since infinite cost usually is the result of parameters going out-of-bound I think the most sensible approach is to require users to limit their parameters.

I'm closing this issue because I think the problem was with your script.
If you are still having problems, feel free to re-open it.
(I noticed a problem with limiting parameters with the scipy optimizer, I'm currently looking into it.)
