### ISSUE TITLE
kafe2.matplotlibrc.conf changes standart plotting settings

### ISSUE THREAD

**Issue by JonasEppelt** [dsavoiu/kafe2#111]
**Describe the bug**
After importing kafe2, some functions for plotting do not work correctly:
  - histograms with `histtype = 'step` are invisible
  - 'x' and '+' as point styles do not display
  - the y- axis is always set on the highest value in the data set, making plots harder to read

These are the issues I found.
As far as I understand it all of these come from the matplotlibrc.conf. 
Is there a way, that the config does not overwrite all these standard settings?

**Comment by JohannesGaessler** [comment]
If I understand you correctly: importing kafe2 is affecting regular matplotlib plots *not* performed with kafe2.

It seems that the kafe2.config module automatically loads the kafe2.matplotlibrc.conf file upon import and changes the global matplotlib configuration.
In turn, kafe2.config is automatically imported when importing kafe2.
I will look into this issue.

In the meantime, you should be able to restore the matplotlib standard settings via `matplotlib.rcdefaults()`.

**Comment by JohannesGaessler** [comment]
I've pushed a fix for this issue: https://github.com/dsavoiu/kafe2/pull/113.
Please confirm whether it works for you.

**Comment by JonasEppelt** [comment]
Yes, the plots not performed by kafe2 where affected. The fix #113 fixed the problems I've had. Thanks!
