### ISSUE TITLE
Replace HistFit numerical integration with Simpson's rule

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#115]
Currently the HistFit uses a general approach to numerically integrate the contents of bins.
This can probably be replaced with applying [Simpson's rule](https://en.wikipedia.org/wiki/Simpson%27s_rule) instead which would probably be faster.

**Comment by Citiroller** [comment]
This would also benefit my use case for the histogram multifit of the lande factor for the myon.
See this script: https://github.com/Citiroller/Bachelor-Thesis-Scripts/blob/master/lande_factor.py
Please replace the kafe2 imports when testing with this script as it uses the kafe2 version supplied as git submodule in the reposittory.


Currently plotting takes forever as well as the antiderivative of the model is recalculated when plotting. (This shouldn't be necessary?).
Enabling asymmetric errors adds a lot of time as well. But I think this has to do with the fit recalculation for asymmetric errors. But this (maybe) uses the antiderivative as well?

I definitely need to check the other cases in more detail, but I think speeding up the integration will increase runtime for this example drastically.
