### ISSUE TITLE
One-sided parameter limts

### ISSUE THREAD

**Issue by ralfulrich** [dsavoiu/kafe2#124]
You provide two-sided limits with  ```limit_parameter(par_name, par_limits)``` it would be great to extend the interface by also a one-sided version. It might be just:
```limit_parameter_low(name, limit)```
```limit_parameter_up(name, limit)```

**Note:** for people using the named parameters in function (as me) it would be nicer if obvious parts are removed, e.g.   ```limit_parameter(name, limits)``` instead of  ```limit_parameter(par_name, par_limits)```  see also #123

**Comment by Citiroller** [comment]
From #123:
I am not sure about `limit_parameter` but I think to explicitly have lower_bound and upper_bound is much better than having a tuple par_limits.
This can be changed together with this request.

**Comment by JohannesGaessler** [comment]
I refactored the interface of limit_parameter.
The method now takes three arguments: name, lower, upper.
One-sided parameters can be achieved by setting only one out lower upper.
