### ISSUE TITLE
Changing global matplotlib rcparams (#113) on Windows Systems

### ISSUE THREAD

**Issue by a-monsch** [dsavoiu/kafe2#126]
**Describe the bug**
This bug seems to be related to [Issue 111](https://github.com/dsavoiu/kafe2/issues/111) and [Fix 113](https://github.com/dsavoiu/kafe2/pull/113). When trying to preserve the default plotting settings, a folder will be opened, which seems not to work on a Windows system (see traceback).

**To Reproduce**
On a Windows 10 system
``` import kafe2 as K2 ```

**Expected behavior**
Obviously it is expected that the default matplotlib settings will be preserved and no PermissionError will occur.

It tries to open a directory as a file, which seems to work on Linux (the bug not appears there) but not on Windows.

Either open an explicit file in the tmp folder or make sure that the file to be opened "file" is not a folder?

**Traceback**
```
File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\kafe2-2.0.dev0-py3.8.egg\kafe2\__init__.py", line 5, in <module>
    from .config import *
  File "C:\Program Files\Python38\lib\site-packages\kafe2-2.0.dev0-py3.8.egg\kafe2\config\__init__.py", line 79, in <module>
    kafe2_rc = mpl.rc_params_from_file(_fake_file.name)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\__init__.py", line 984, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\__init__.py", line 914, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "C:\Program Files\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Program Files\Python38\lib\site-packages\matplotlib\__init__.py", line 900, in _open_file_or_url
    with open(fname, encoding=encoding) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\a-monsch\\AppData\\Local\\Temp\\tmpxxd5vibu'
```

**System:**
 - OS: Windows10
 - Python Version: 3.6.9, 3.8.1

**kafe2-version**
Latest master branch (10.04.2020)

**Additional context**
It was made sure that everything was done/executed as administrator/with administrator rights.

**Comment by JohannesGaessler** [comment]
I was able to reproduce the issue and pushed a fix onto master.
However, in my case the path that kafe2 tried to open was **not** a directory.
I think the problem instead had to do with OS-specific management of file handles for temporary files.
If the problem persists on your machine, please re-open this issue.

**Comment by a-monsch** [comment]
> I think the problem instead had to do with OS-specific management of file handles for temporary files. 

Nice to know that. It is fixed now, thank you for the fast respond!
