### ISSUE TITLE
NDF is not always correct

### ISSUE THREAD

**Issue by ralfulrich** [dsavoiu/kafe2#128]
**Describe the bug**
The n.d.f. are not computed correctly, only **free** parameters may be subtracted from the number of input data points. 

**To Reproduce**
See example here, slightly modified from your documentation example: 
```
from kafe2 import XYFit, Plot, XYContainer
import matplotlib.pyplot as plt

xy_data = XYContainer(x_data=[1.0, 2.0, 3.0, 4.0], y_data=[2.3, 4.2, 7.5, 9.4])
xy_data.add_error(axis='y', err_val=0.4)

line_fit = XYFit(xy_data=xy_data)

# THE NEXT LINE PROVOKES THE ERROR: 
line_fit.fix_parameter('a', 2.4)

line_fit.do_fit()  
r = line_fit.get_result_dict()
print (str(r))

line_fit.report()

plot = Plot(fit_objects=line_fit)  
plot.plot() 
plt.show()
```

**Expected behavior**

N.D.F = (number of input data points) - (number of FREE parameters)

Fixed parameters are not counted for n.d.f.

**System:**
jupyter-lab on ubuntu

**Comment by JohannesGaessler** [comment]
Fixed.
