### ISSUE TITLE
bug introduced after recent update

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#134]
In Chap.2 (Vergleich von zwei Modellen) of testKafe2.ipyng
there is a bug (leading to a crash) after one of the recent updates
in fit.report():

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-8bb7c656b71f> in <module>
----> 1 exponential_fit.report(asymmetric_parameter_errors=True)
      2 exponential_fit.get_result_dict()

/usr/lib/python3.6/site-packages/kafe2/fit/_base/fit.py in report(self, output_stream, show_data, show_model, show_fit_results, asymmetric_parameter_errors)
    859         if show_fit_results:
    860             self._report_fit_results(output_stream=output_stream, indent=_indent, indentation_level=0,
--> 861                                      asymmetric_parameter_errors=asymmetric_parameter_errors)
    862 
    863     def to_file(self, filename, file_format=None, calculate_asymmetric_errors=False):

/usr/lib/python3.6/site-packages/kafe2/fit/_base/fit.py in _report_fit_results(self, output_stream, indent, indentation_level, asymmetric_parameter_errors)
    196                                   with_errors=True,
    197                                   format_as_latex=False,
--> 198                                   asymmetric_error=asymmetric_parameter_errors)
    199             )
    200             output_stream.write('\n')

/usr/lib/python3.6/site-packages/kafe2/fit/_base/format.py in get_formatted(self, with_name, with_value, with_errors, n_significant_digits, round_value_to_error, asymmetric_error, format_as_latex)
    193 
    194             if not with_errors or (not asymmetric_error and self.error in (None, 0)) or \
--> 195                     (asymmetric_error and self.asymmetric_error in (None, (0, 0))):
    196                 if format_as_latex:
    197                     _display_string += "$%g$" % self.value

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by JohannesGaessler** [comment]
I pushed a fix onto master.
Sorry about this; I thought the changes I made were covered by unit tests and did not notice this.
