### ISSUE TITLE
example 202_cost_functions does not work

### ISSUE THREAD

**Issue by ralfulrich** [dsavoiu/kafe2#146]
python3 01_poisson_cost_function.py 
Traceback (most recent call last):
  File "01_poisson_cost_function.py", line 64, in <module>
    xy_fit = XYFit(
  File "/home/lecture/cgda_env/lib/python3.8/site-packages/kafe2/fit/xy/fit.py", line 89, in __init__
    raise XYFitException('Unknown cost function: %s' % cost_function)
kafe2.fit.xy.fit.XYFitException: Unknown cost function: nll-poisson

**Comment by JohannesGaessler** [comment]
Are you perhaps using the example on Github with the kafe2 version installed via pip?

**Comment by ralfulrich** [comment]
Yes, this is what I do. I would expect this to be the default way to install and run kafe2...

**Comment by Citiroller** [comment]
The cost functions got updated on the current master branch and the examples were adapted, to fit the new code base.
Those changes did not yet make it into a new release.
Those changes simplify the code base drastically and also simplify the usage of cost functions.
You can either use the current version from the master branch or use the examples from the current v2.0 branch https://github.com/dsavoiu/kafe2/tree/v2.0/examples
Another solution would be to change this part (the new way!) (line 64-):
```
xy_fit = XYFit(
    xy_data=[years_of_death, measured_c14_activity],
    model_function=expected_activity_per_day,
    cost_function="nll-poisson"
)
```
into this (the old way!):
```
xy_fit = XYFit(
    xy_data=[years_of_death, measured_c14_activity],
    model_function=expected_activity_per_day,
    cost_function='nll'  # or 'negloglikelihood' or 'neg_log_likelihood'
)
```
Likelihood cost functions for XYFits did use a poisson distribution for the y-uncertainties by default.
In the new master branch this needs to be specified and either `'nll-poisson'` or `'nll-gaussian'` are valid identifiers.

**Comment by Citiroller** [comment]
@JohannesGaessler maybe we should make the v2.0 branch the default branch when visiting the github page. This would avoid confusion with the ongoing development.

**Comment by JohannesGaessler** [comment]
@ralfulrich 
I agree that this is the expected way for users to use kafe2.
I just wanted to make sure that my understanding of the problem is correct.
I published a new release that should fix the discrepancy between the version on PyPI and the Github repository; just upgrade kafe2 with pip.
If this doesn't fix the problem, please re-open this issue.

@Citiroller 
I think we should instead just make more releases.
This is one of the points that we will discuss on Wednesday.
