### ISSUE TITLE
latest version complains if errors == 0 in block of correlated errors

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#147]
however, this is quite frequent when blocks of correlated errors are specifies, e.g.
   
  17 err_stat = idx_data.add_error([.2, .2, .2, .2])
     18 # - eine den ersten beiden Werten gemeinsame Unsicherheit
---> 19 err_syst12 = idx_data.add_error([.175, .175, 0., 0.], correlation = 1.)
     20 # - eine den letzten beiden Werten gemeinsame, relative Unsicherheit
     21 err_syst34 = idx_data.add_error([0., 0., .05, 0.05], correlation = 1., relative=True)

kafe2 uncorrectly throws an error in the line marked with --->

**Comment by JohannesGaessler** [comment]
Fixed
