### ISSUE TITLE
Warnung \mathcal{L}

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#149]
Bei der Ausgabe des symbols \mathcal{L} in allen Fit-Typen, die eine Likelihood ausgeben,
 tritt (neuerdings) folgende Warnung auf: 

WARNING:matplotlib.mathtext:Substituting symbol L from STIXNonUnicode

Nicht schön ... 
Vorschlag: Unicode ℒ (U+2112) verwenden ...

Problem verschwindet mit matplotlib 3.3.1 - kann also geschlossen werden.

**Comment by Citiroller** [comment]
I can't replicate this issue.
Which version of matplotlib are you using?
Can you provide an example script? I tried example 006 for the unbinned likelihood fit, which does not produce the warning for me.
