### ISSUE TITLE
Unexpected behavior when x is not first argument

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#15]
If you specify am xy model function that has an argument other than x as its first argument it will treat the first argument as x.
For example the model function f(x, a, b) = a * x + b is interpreted as follows when changing the order of the parameters:
f(b, a, x) = a * x + b = c + b, with c being a real number.

**Comment by JohannesGaessler** [comment]
When the first argument is self XYMultiFit objects treat x as a parameter.

**Comment by Citiroller** [comment]
Is this still a thing?
Somehow related to this would be a feature for allowing different names than `x` for the x-data parameter. Currently it's hardcoded in every constructor of the `ModelFunction` classes.

**Comment by Citiroller** [comment]
Looking at this again, I don't think the data parameter should always be x, but the first parameter of the function. kafe2 is a tool aimed at students learning about fits and should use pedagogical/didactic methods for easier understanding.
When writing Ohm's law for example, it's quite unusual to see it like this:
```
def u(x, r=1):
  u = r*x
  return u
```
And every student would ask, why the current is named x and not i.
I think we should allow the user to choose whatever variable name thy want and use the first variable for the data.
Then ohm's law would look like this:
```
def u(i, r=1)
  u = r*i
  return u
```

**Comment by Citiroller** [comment]
#93 now changes the way the independent variable is handled. For all fits, except indexed fit it's now the first argument of a function.
This approach was made modular and can be easily changed if, for example we introduce a fit which requires two independent data inputs or similar.
