### ISSUE TITLE
List keywords in kafe2go help

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#151]
As of right now kafe2go has no way of listing all valid keywords and their functions on the command line.
I think implementing this feature would make the tool much more convenient because you wouldn't need to switch to the documentation while you're working with it.

**Comment by Citiroller** [comment]
The valid keywords are currently not stored anywhere central. I would need to look at every single `yaml_drepr.py` inside `./kafe2/representation/*` to find all valid keywords. Do you have an idea on how to store them centrally and access them when building the documentation?
