### ISSUE TITLE
MultiFit.set_all_parameter_values causes a crash in PyPI v2.4.0-pre2

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#172]
MultiFit.set_parameter_values and MultiFit.set_all_parameter_values caused crashes in v2.4.0-pre1.
I was tired when writing a quick fix for https://github.com/dsavoiu/kafe2/issues/171 and accidentally only pushed a partial fix.
I deleted the corresponding release on Github afterwards and made a new release with a full fix.
The release on PyPI did **not** get replaced however.
Because of this MultiFit.set_all_parameter_values still causes a crash when v2.4.0-pre2 is installed from PyPI even though the issue was fixed.

**Comment by cverstege** [comment]
This should be solved now as we have a full 2.4.0 release and a full 2.5.0 one.
