### ISSUE TITLE
access to profile likelihood for arbitrary interval

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#198]
For special fits, e.g. he determination of a "Significance" of a paramter value being different from zero, or for limit setting, a function to obtain the profile likelihood
would be very much appreciated. In iminuit, this is provided by the function
iminuit.mnprofile(pnam, bound = range, size=npoints, subtract_min=True)

**Comment by JohannesGaessler** [comment]
Question regarding the implementation: are the features provided by iminuit sufficient?
Internally iminuit.mnprofile is being used by default.
If additional functionality is required that would require a manual implementation.
For example, would it be necessary to specify non-equidistant points for he profile?

**Comment by GuenterQuast** [comment]
yes, the iminuit features are sufficient; this feature is needed mostly far away from the minimum ...

**Comment by JohannesGaessler** [comment]
Done.
