### ISSUE TITLE
Cost Function "HistCostFunction_GaussApproximation"

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#199]
Concerning Histogram Fits with Gaussian Approximation:
 the appropriate cost function  kafe2/fit/_base/CostFunction_GaussApproximation should be include in kafe2/fit/histogram/cost.py:

class HistCostFunction_GaussApproximation(CostFunction_GaussApproximation):
    pass

**Comment by JohannesGaessler** [comment]
done
