### ISSUE TITLE
ROOT installation instructions not working

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#21]
The readme gives installation instructions for ROOT via the package manager.
However, when I tried installing ROOT this way it didn't work because apt could not find the described packages.
Is it perhaps necessary to add a repository first?

**Comment by dsavoiu** [comment]
It seems ROOT has been removed from the official Ubuntu repositories
in Ubuntu 16.10. I will update the instructions to reflect this.
