### ISSUE TITLE
Error band undersampling for large datasets

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#25]
Currently the error bands for xy fits always use 50 data points for their calculation.
For model functions with > 50 data points and nonlinear behavior this causes undersampling and the error band can look like it doesn't fit the data at all.
Sine and cosine functions in particular are being affected.

**Comment by Citiroller** [comment]
In #116 the support points for the error band and model are now dynamically set to two times the data points but 100 points at least for the XYFit. Dou you think this is enough @JohannesGaessler or should I change the factor to two or three?
For the HistFit and Unbinned Fit I've changed the amount of support points to the number of datapoints/bins but 100 at least (factor 1).
Dou you think those factors are good? Changing them is can be done by adapting the n_plot_points attribute in the fit adapters.
