### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by Citiroller** [dsavoiu/kafe2#44]
The unit tests are currently all failing on the travis system.
The reseon seems to be Travis running the test twice. The first run is fine, but when it tries to run the tests a second time, a numpy import error will fail the tests.

**Comment by dsavoiu** [comment]
Should be fixed now. It seems that `python setup.py test` was indeed running the test suite twice. I couldn't figure out why, but changing the test command to `python -m unittest kafe2/test -p "*.py"` solved the problem.
