### ISSUE TITLE
Better spacing between function and parameters for asymmetric errors

### ISSUE THREAD

**Issue by Citiroller** [dsavoiu/kafe2#54]
When using a latex expression for the fit function including a fraction, the expression overlaps with the upper asymmetric error from the first parameter.

**Comment by dsavoiu** [comment]
Addressed by #56

**Comment by Citiroller** [comment]
@dsavoiu is this issue resolved? This PR is closed, but doesn't seem to be merged. Did you cherry pick those commits into master?

**Comment by dsavoiu** [comment]
@Citiroller The changes are definitely on `master`. Not sure why the PR status is `closed` instead of `merged`. Could be that I rebased the changes onto `master` and GitHub didn't correctly pick up on that... Closing this issue.
