### ISSUE TITLE
Histogram fit constructor docstring is wrong

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#6]
The docstring for the `HistFit` constructor states that `data` should be an iterable of float.
However, the constructor actually expects `data` to be a `HistContainer` object.
Presumably the docstring was just copied from another fit class and not changed.

What is the intended data format for `HistFit`?
Should the docstring or the code be changed?

**Comment by dsavoiu** [comment]
The docstring should be changed. Fixed by e4906a.
