### ISSUE TITLE
Asymmmetric and symmetric errors seem to differ drastically with Multifit

### ISSUE THREAD

**Issue by Citiroller** [dsavoiu/kafe2#64]
This needs more investigation!
When using `plot.plot(with_asymmetric_parameter_errors=True)` for a Multifit, the value of the cost functions, as well as the scale of the parameter uncertainties seem to change quite drastically.

For example the uncertainty for omega is about ten times higher when using the asymmetric parameter errors. The error for A_0 is about 100 times bigger with the symmetric errors.

The following pictures show the exact same fit, the only difference is the asymmetric parameter error when plotting the results,
![lande_fit_sym](https://user-images.githubusercontent.com/6241018/69672806-2715c400-1099-11ea-8f1f-27d0f2f14ac4.png)
![lande_fit_asym](https://user-images.githubusercontent.com/6241018/69672799-254c0080-1099-11ea-9a42-db1827837c61.png)

The fit was performed using the iminuit minimizer.

**Comment by Citiroller** [comment]
The script producing the plots can be found here: https://github.com/Citiroller/Bachelor-Thesis-Scripts/blob/master/lande_factor.py

**Comment by JohannesGaessler** [comment]
I think I've found the bug behind this problem.
Apparently there was a bug with how the Nexus graph handled dependencies: some nodes X had Y as parents but Y did not have X as children.
The results from your example script seem reasonable now, but I'll need some more work to finalize my changes.
I'll probably make a PR tomorrow.

Console output generated with a modified version of your script:
`tau: 2.196E+00 +- 5.130E-03
k_top: 8.669E-01 +- 3.200E-03
a_bar_top: 4.021E-03 +- 1.928E-03
omega: 3.138E+00 +- 1.893E-01
delta: 4.627E+00 +- 9.136E-01
f_top: 2.173E-02 +- 1.081E-04
k_bot: 8.403E-01 +- 3.367E-03
a_bar_bot: 3.911E-13 +- 4.478E-04
f_bot: 2.389E-02 +- 1.460E-04

Model Parameters
================

    tau = 2.1959 + 0.0051 (up) - 0.0051 (down)
    k_top = 0.8669 + 0.0032 (up) - 0.0032 (down)
    a_bar_top = 0.004 + 0.0019 (up) - 0.0019 (down)
    omega = 3.14 + 0.18 (up) - 0.27 (down)
    delta = 4.63 + 1.07 (up) - 0.93 (down)
    f_top = 0.02173 + 0.00011 (up) - 0.00011 (down)
    k_bot = 0.8397 + 0.0034 (up) - 0.0034 (down)
    a_bar_bot = 1.5334e-08 + 0.000459121 (up) - 6.6e-14 (down)
    f_bot = 0.02374 + 0.00015 (up) - 0.00015 (down)`

**Comment by Citiroller** [comment]
The new results look very good. Now the symmetric uncertanties seem to be similar to the asymmetric ones. Thanks for investigating it.

Am Samstag, den 30.11.2019, 15:14 -0800 schrieb JohannesGaessler:

I think I've found the bug behind this problem.
Apparently there was a bug with how the Nexus graph handled dependencies: some nodes X had Y as parents but Y did not have X as children.
The results from your example script seem reasonable now, but I'll need some more work to finalize my changes.
I'll probably make a PR tomorrow.

Console output generated with a modified version of your script:
`tau: 2.196E+00 +- 5.130E-03
k_top: 8.669E-01 +- 3.200E-03
a_bar_top: 4.021E-03 +- 1.928E-03
omega: 3.138E+00 +- 1.893E-01
delta: 4.627E+00 +- 9.136E-01
f_top: 2.173E-02 +- 1.081E-04
k_bot: 8.403E-01 +- 3.367E-03
a_bar_bot: 3.911E-13 +- 4.478E-04
f_bot: 2.389E-02 +- 1.460E-04

Model Parameters

tau = 2.1959 + 0.0051 (up) - 0.0051 (down)

k_top = 0.8669 + 0.0032 (up) - 0.0032 (down)

a_bar_top = 0.004 + 0.0019 (up) - 0.0019 (down)

omega = 3.14 + 0.18 (up) - 0.27 (down)

delta = 4.63 + 1.07 (up) - 0.93 (down)

f_top = 0.02173 + 0.00011 (up) - 0.00011 (down)

k_bot = 0.8397 + 0.0034 (up) - 0.0034 (down)

a_bar_bot = 1.5334e-08 + 0.000459121 (up) - 6.6e-14 (down)

f_bot = 0.02374 + 0.00015 (up) - 0.00015 (down)`

**Comment by Citiroller** [comment]
It would be nice to have this fix in a new release, which I can then use in my thesis, before it gets published. I would need to update one plot.
But this is not necessary for the thesis hand-in.

**Comment by Citiroller** [comment]
Fixed in #67

**Comment by Citiroller** [comment]
Fixed by #67 
This issue will close automatically when #67 is merged.
