### ISSUE TITLE
macOS Python 2.7 compatibility

### ISSUE THREAD

**Issue by cverstege** [dsavoiu/kafe2#73]
macOS 10.15.2 mit Python 2.7 über MacPorts
- kafe2go wurde in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin installiert und war nicht automatisch im Pfad
- Beispiel 001, 002, 006, 101 (da habe ich aufgehört zu testen) haben Probleme mit dem tkagg Backend:  
        from matplotlib.backends import _tkagg
        ImportError: cannot import name _tkagg
  → anscheinend liegt das an der Reihenfolge der Importe. Wenn ich matplotlib.pyplot *vor* kafe2 importiere, funktionieren die Beispiele (zumindest 001 und 002). 
- Ich habe dann kafe2 auch noch für Python 3.8 installiert. Da gibt es obiges Problem mit tkagg nicht.

**Comment by Citiroller** [comment]
This seems to be a bug of the apple supplied python!
See https://www.python.org/download/mac/tcltk/ for more information.

**Comment by cverstege** [comment]
Python 2 has been EOL since over a year: https://www.python.org/doc/sunset-python-2/

We also do recommend using Python3 with kafe2.

Won't fix this issue, closing.
