### ISSUE TITLE
example 101 multifit error 

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#74]
- Beispiel 201_kafe2go multifit gibt Fehler
    No `PlotAdapter` configured for fit type 'XYMultiFit'!

**Comment by JohannesGaessler** [comment]
This issue seems to be outdated.
The current implementation of the multifit example no longer uses XYMultiFit and should be running correctly.
Reopen if it doesn't for you.

**Comment by Citiroller** [comment]
The old file is still present here https://github.com/dsavoiu/kafe2/blob/master/examples/201_kafe2go_advanced/multifit.yml as I moved the advanced examples to another folder while creating the tutorial for later use in the advanced tutorial.
If the new multifit example is identical, this file can be removed.
