### ISSUE TITLE
result grafics: no (obvious) way to change axis labels; such functionality must be provided, 

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#76]
- Ergebnisgrafik - Setzen der Achsenbschriftungen:
  die können nicht immer x oder y sein, sondern müssen
  vom Nutzer definierbar sein; das sind Eigenschaften der
  Daten und sollten dort definiert werden, z.b.
  (x-data_label: 'time (s)', y-data_label: 'Amplitude (cm)')

**Comment by Citiroller** [comment]
This is currently not supported and will be added soon.

As a workaround do:
```
plot.plot()  # plot the fit(s)
plot.axes[0]['main'].set_xlabel('x_name')  # change the x-axis label
plot.axes[0]['main'].set_ylabel('y_name')  # change the y-axis label
```

**Comment by Citiroller** [comment]
Duplicate of #31, closing this issue.
For further discussion please refer to #31
