### ISSUE TITLE
configuration options for graphics: need functionality to override default configs, eg. in ~/.config/kafe2 and in work directory

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#77]
- Konfigurationsoptionen für Grafiken:
  müssen vom Nutzer gesetzt werden können,
  Empfehlung: falls config-Datei kafe2.matplotlibrc.conf
  in ~/.config/kafe2 oder im Arbeitsverzeichis, so führt zum
  Überschreiben der configs im kafe2-Installationsverzeichnis

**Comment by cverstege** [comment]
kafe2 should now respect config files stored in the current working directory (ae3f45165f8ee4f5d98e622552e4c06c3c853a0b).
Not yet thoroughly tested though!

If we want to use e.g. `~/.config/kafe2/` we would need a cross platform compatible library, e.g. [AppDirs](https://pypi.org/project/appdirs/)

The config files must be named `kafe2.yaml` (which can include yaml imports via `!`) and `kafe2.matplotlib.rc.conf`. One can use the files located in the [kafe2 config folder](https://github.com/dsavoiu/kafe2/tree/master/kafe2/config) as templates.
