### ISSUE TITLE
2ln(L) for Histogram fits not meaningful - think about normalisation (e.g. wiht reference to "fully saturated model")

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#79]
2 ln(L)/ndf für Histogrammfits: kann so (auch im Grenzfall großer
  Stichproben) nicht mit chi2/ndf gleichgesetzt werden. Darüber
  müssen wir noch einmal nachdenken ... der Wert der Likelihood
  am Minimum muss passend normiert werden; üblicherweise nimmt
  man dazu den Wert, der sich ergibt, wenn alle Datenpunkte exakt
  auf dem Modell liegen, also ln(L_norm) = ln(L(n_i|m_i)) - ln(L(m_i|m_i))
  Im Grenzfall sollte chi2 herauskommen !

**Comment by Citiroller** [comment]
This exact cost function can be used in a histogram fit by passing the parameter `cost_function='nllr'` when creating the HistFit object.
Should this cost function used as the default instead with the HistFit @GuenterQuast?
The according lines of the current implementation:
https://github.com/dsavoiu/kafe2/blob/6a293f4fb85eb1085616653230ceb40f74f771e1/kafe2/fit/_base/cost.py#L638
```
        _total_log_likelihood = np.sum(poisson.logpmf(k=data, mu=model, loc=0.0))
        _saturated_log_likelihood = np.sum(poisson.logpmf(k=data, mu=data, loc=0.0))
        _log_likelihood_ratio = _total_log_likelihood - _saturated_log_likelihood
```

**Comment by cverstege** [comment]
Closed with e550a5e and 592fd75.
Use property:
`XYFit.chi2_probability`
or in general:
`Fit.goodness_of_fit`

This information is also given in the terminal and graphical outputs.
