### ISSUE TITLE
suggestion of simpler user interface

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#80]
compared to kafe(1), the user interface of kafe2 is quite complicated

**suggestions:** 

 - a wrapper class "Fit" avoiding XYFit, IndexedFit, etc. - the kind of fit is determined
   by the container object

- as single method add_error(); again, add_simple_error or add_matrix_error are clearly
  distinguishable by the argument list (err_matrix=None)

**Comment by Citiroller** [comment]
Sorry I forgot to assign and close this issue. Implemented in a70334f0686c6cf692e0d5bd0e613f7e064fca05
