### ISSUE TITLE
plot layout: x and y plot range

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#85]
Most plot look very "squeezed" because the plot range in x and y is chosen to just fit the
data points +/- error bars; the 2-sigma contours often are even cropped.

request: make default 10% larger in (xmin, xmax) and (ymin, max) than is presently set
 (this should then be ok in most cases and will look much nicer)
suggestion: provide simple(!) method to conifiure, eg. as an option to the plot()-method

**Comment by Citiroller** [comment]
#116 has been merged. It's now possible to manually set the plot range via the x_range and y_range properties.
The default values have not been changed. If that's still a problem please open a separate bug report.
