### ISSUE TITLE
set name of inependent variable (x) in graphical output

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#86]
In most practcial examples the name of the variable on the x-axis is not "x". 
This convention in kafe2 is ~ok for specifying the code of the model function, but not acceptable in the graphical output - here, a possibility must be provided to specify another symbol reflection 
the real nature of the x-data (e.g A for amplitude, E for energy, Phi for phase, ...)

**Comment by Citiroller** [comment]
I want to simplify the function formatting classes soon. I'll keep this in mind when doing so.
