### ISSUE TITLE
precision of unctainty printed on profile curves too high

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#87]
there is a general agreement that uncertaindies are specified with a precision of two non-zero digits; the output on the profile-curves specifies too many digits; 

Ideally, the number of digits given on the average should reflect the same precision
(as is done in the print-out of the fit results in the main graphics)

**Comment by Citiroller** [comment]
https://stackoverflow.com/questions/51845794/matplotlib-tick-label-precision
