### ISSUE TITLE
model name in graphical output

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#88]
If no latex-name is specified, the string =<not specified> is shown; 
this is ugly and should be replaces by ' ' (including the '=' sign)

**Comment by Citiroller** [comment]
This behaviour should not be present anymore. If no latex expression for a function is specified, only the function name and parameters are shown. If a latex-name is specified, the altex name instead fo the function name is shown.
If a latex expression for the function (not the function name) is specified, `' =  ' + latex_expression` is appended.
Is this the desired behavior as it is right now @GuenterQuast?
