### ISSUE TITLE
kafe2/matplotlib import order

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#9]
Some examples state that it's important to import matplotlib after kafe2.
However, I did not notice a difference or problem when I imported matplotlib first.

**Comment by Citiroller** [comment]
#73 is an example of this.
By importing kafe2 first, matplotlib will use the kafe2 config and in this case try to use the tkagg backend.
This will result in an error however.
By importing matplotlib first, matplotlib will initialize before kafe2 and use another backend.

So when importing matplotlib before kafe2, not all custom matplotlib settings from kafe2 are taken into account.

**Comment by cverstege** [comment]
This is a problem using kafe2 in jupyter notebooks:

> Einige Studierende und auch die Bonner hatten Probleme in jupyter mit der
> Interferenz zwischen kafe2 und matplotlib - wenn man matplotlib vor kafe
> importiert, oder auch Komponenten von kafe2 nach matplotlib, dann gibt
> es bisweilen gar keinen output, oder der output erscheint in Fenstern
> statt im Notebook, oder es gibt kryptische Fehlermeldungen vom backend,
> die im Notebook auftauchen (die man nicht versteht und die nerven).
> Das hat zu einigen Anfragen geführt, die ich dann mit dem Hinweis
> "immer kafe2 vor matplotlib importieren" fixen konnte. Hat jemand
> eine Idee, wie sich das vermeiden oder entschärfen ließe ?

We should look into this soon, pinning this issue, so that everyone sees the fix for now:
Import kafe2 before matplotlib

**Comment by cverstege** [comment]
Hopefully fixed with c96a53c3d646f38b19cd88cc0bc28a925322efad
