### ISSUE TITLE
problem with xyFit.disable_error()

### ISSUE THREAD

**Issue by GuenterQuast** [dsavoiu/kafe2#91]
disabling error components is only useful if they can be re-enabled; unfortunately
xyFit.enable_error() does not work (works in xyContainer, but disabling/enabling errors
there requires setting up a new xyFit-object for each study - very annoying).

**Comment by Citiroller** [comment]
This should be working as of  8199e89. If not please reopen the issue. I did not test it, but the fix seemed to be very straight forward.

**Comment by Citiroller** [comment]
Seems like the methods `_initialize_fitter()` and maybe `_init_nexus() ` have to be called in order for this working properly.
Maybe @JohannesGaessler knows more about the internal workings of the Nexus and Fitter implementations.
